### ISSUE TITLE
difference with Lacouture paper?

### ISSUE THREAD

**Issue by anne-urai** [bramzandbelt/exgauss#1]
Hi Bram, thanks for a nice little toolbox! I also found this code http://www.psy.ulaval.ca/?pid=1529 by Yves Lacouture, who wrote the tutorial article. Is there any specific reason why you reimplemented the code rather than using the provided code?

**Comment by bramzandbelt** [comment]
Hi Anne, thanks for your message. I wrote this piece of code merely as an exercise in version control, Github, and clear coding. There are a few minor differences with respect to Lacouture's toolbox in terms of the optimization algorithm (bounded Simplex), plotting (cumulative distribution function), and output (Pearson's Chi-square goodness-of-fit statistic).
